remote_theme: raviriley/agency-jekyll-theme
# SITE SETTINGS
title: The McComb Lab                   # Title in top navigation bar (navbar) and <head>
description: Jekyll theme for research project websites # Site description in <head>
author: Peter Desmet                    # Used for copyright statement in footer
